openapi: 3.0.3
info:
  title: Builder Templater API
  version: 1.0.0
  description: API for provisioning user sites

paths:
  /domain/check:
    post:
      summary: Checks domain availability
      description: Returns whether a domain is available or not
      operationId: checkDomain
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckDomainParams'
      responses:
        '200':
          description: Domain availability info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainAvailability'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /provision/healthcheck:
    post:
      summary: Run healthchecks on site's provision
      description: Returns whether a site is healthy or down
      operationId: provisionHealthcheck
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HealthcheckProvisionRequest'
      responses:
        '200':
          description: Domain availability info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthcheckProvisionResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /provision:
    post:
      summary: Provision a new site
      description: Provisions a site with a given template name, domain variants, and additional configuration fields.
      operationId: provisionSite
      tags:
        - Sites
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProvisionSiteRequest'
      responses:
        '201':
          description: Site provisioned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProvisionSiteResponse'
        '400':
          description: Invalid request format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error during provisioning
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ProvisionSiteRequest:
      type: object
      properties:
        siteID:
          type: integer
          format: uint64
          example: 101
        domainType:
          type: string
          enum: [DefaultDomain, SeparateDomain, BringYourDomain]
        templateName:
          type: string
          example: template1
        domain:
          type: string
          example: "example.com"
        fields:
          type: object
          description: json object with all widgets and fields of a site
          additionalProperties: true
      required:
        - siteID
        - domainType
        - templateName
        - domain
        - fields

    ProvisionSiteResponse:
      type: object
      properties:
        siteID:
          type: integer
          format: uint64
          example: 101
      required:
        - siteID

    CheckDomainParams:
      type: object
      properties:
        domain:
          type: string
      required:
        - domain
    HealthcheckProvisionRequest:
      type: object
      properties:
        siteID:
          type: integer
          format: uint64
          example: 101
      required:
        - siteID

    HealthcheckProvisionResponse:
      type: object
      properties:
        status:
          type: string
          enum: [Healthy, Unhealthy, NotProvisioned]
      required:
        - status

    DomainAvailability:
      type: object
      properties:
        available:
          type: boolean
          example: true
      required:
        - available

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "invalid request"
      required:
        - error