services:
  postgres:
    image: postgres:17.2-alpine
    container_name: postgres
    hostname: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: builder
      POSTGRES_USER: sanity
      POSTGRES_PASSWORD: wordpass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/users:rw
      - ./config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.0
    hostname: keycloak
    container_name: keycloak
    environment:
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      HTTP_ADDRESS_FORWARDING: true
      KC_PROXY_HEADERS: xforwarded
    expose:
      - 7080
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7080/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command: [ "start-dev", "--http-port", "7080", "-Djava.net.preferIPv4Stack=true"]
    depends_on:
      jodrive-db:
        condition: service_started
    volumes:
      - ./config/keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      keycloak:
        condition: service_started
    volumes:
      - ./config/nginx/conf.dev/:/etc/nginx/conf.d/
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf