services:
  postgres:
    image: postgres:17.2-alpine
    container_name: postgres
    hostname: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: builder
      POSTGRES_USER: sanity
      POSTGRES_PASSWORD: wordpass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - ./config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env.prod
    command: [ "main" ]
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy