// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package dto

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for GetSiteResponseHealthCheckStatus.
const (
	Healthy        GetSiteResponseHealthCheckStatus = "Healthy"
	NotProvisioned GetSiteResponseHealthCheckStatus = "NotProvisioned"
	Unhealthy      GetSiteResponseHealthCheckStatus = "Unhealthy"
)

// Defines values for UpdateSiteRequestDomainType.
const (
	BringYourDomain UpdateSiteRequestDomainType = "BringYourDomain"
	DefaultDomain   UpdateSiteRequestDomainType = "DefaultDomain"
	SeparateDomain  UpdateSiteRequestDomainType = "SeparateDomain"
)

// Defines values for UpdateSiteRequestNewStatus.
const (
	AwaitingProvision UpdateSiteRequestNewStatus = "AwaitingProvision"
	Created           UpdateSiteRequestNewStatus = "Created"
	InCreation        UpdateSiteRequestNewStatus = "InCreation"
)

// Defines values for VerifyOauthTokenProvider.
const (
	Google VerifyOauthTokenProvider = "Google"
)

// CreateConfirmation defines model for CreateConfirmation.
type CreateConfirmation struct {
	Email  string             `json:"email"`
	UserID openapi_types.UUID `json:"userID"`
}

// CreatePaymentRequest defines model for CreatePaymentRequest.
type CreatePaymentRequest struct {
	PlanID uint8 `json:"planID"`
	SiteID int64 `json:"siteID"`
}

// CreatePaymentResponse defines model for CreatePaymentResponse.
type CreatePaymentResponse struct {
	ClientSecret   *string `json:"clientSecret,omitempty"`
	SubscriptionID *string `json:"subscriptionID,omitempty"`
}

// CreateSession defines model for CreateSession.
type CreateSession struct {
	AccessToken  string `json:"accessToken"`
	IdToken      string `json:"idToken"`
	RefreshToken string `json:"refreshToken"`
}

// CreateSiteRequest defines model for CreateSiteRequest.
type CreateSiteRequest struct {
	// Fields json object with all widgets and fields of a site
	Fields     *map[string]interface{} `json:"fields,omitempty"`
	PlanID     uint8                   `json:"planID"`
	TemplateID uint8                   `json:"templateID"`
}

// CreateSiteResponse defines model for CreateSiteResponse.
type CreateSiteResponse struct {
	SiteID uint64 `json:"siteID"`
}

// CreateTemplateRequest defines model for CreateTemplateRequest.
type CreateTemplateRequest struct {
	// Fields json object with all widgets and fields of a site
	Fields map[string]interface{} `json:"fields"`

	// Name template's name
	Name string `json:"name"`
}

// CreateTemplateResponse defines model for CreateTemplateResponse.
type CreateTemplateResponse struct {
	Id uint8 `json:"id"`
}

// DeleteUserRequest defines model for DeleteUserRequest.
type DeleteUserRequest struct {
	Email string `json:"email"`
}

// DomainAvailability defines model for DomainAvailability.
type DomainAvailability struct {
	Available bool `json:"available"`
}

// EnrichContentRequest defines model for EnrichContentRequest.
type EnrichContentRequest struct {
	Content string `json:"content"`
}

// EnrichContentResponse defines model for EnrichContentResponse.
type EnrichContentResponse struct {
	Enriched string `json:"enriched"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// FileUploadedResponse defines model for FileUploadedResponse.
type FileUploadedResponse struct {
	FileID  openapi_types.UUID `json:"fileID"`
	FileURL string             `json:"fileURL"`
}

// GetSiteResponse defines model for GetSiteResponse.
type GetSiteResponse struct {
	CreatedAt         string                           `json:"createdAt"`
	HealthCheckStatus GetSiteResponseHealthCheckStatus `json:"healthCheckStatus"`

	// Structure url to pages.json file
	Structure string `json:"structure"`
}

// GetSiteResponseHealthCheckStatus defines model for GetSiteResponse.HealthCheckStatus.
type GetSiteResponseHealthCheckStatus string

// ListTemplateInfo defines model for ListTemplateInfo.
type ListTemplateInfo struct {
	Elements []TemplateInfo `json:"elements"`
	HasNext  bool           `json:"hasNext"`
	Page     int            `json:"page"`
	Total    int            `json:"total"`
}

// ListTemplatePaginator defines model for ListTemplatePaginator.
type ListTemplatePaginator struct {
	Page *int `json:"page,omitempty"`
	Size *int `json:"size,omitempty"`
}

// PaymentPlan defines model for PaymentPlan.
type PaymentPlan struct {
	Description string   `json:"description"`
	Excluded    []string `json:"excluded"`
	Id          uint8    `json:"id"`
	Included    []string `json:"included"`

	// Price Price in cents
	Price int `json:"price"`
}

// PaymentPlanList defines model for PaymentPlanList.
type PaymentPlanList = []PaymentPlan

// PaymentStatusResponse defines model for PaymentStatusResponse.
type PaymentStatusResponse struct {
	PaymentIntentID     string `json:"paymentIntentID"`
	PaymentIntentStatus string `json:"paymentIntentStatus"`
	PaymentStatus       string `json:"paymentStatus"`
	Status              string `json:"status"`
}

// RebuildTemplatesRequest defines model for RebuildTemplatesRequest.
type RebuildTemplatesRequest struct {
	// Name template's name
	Name *string `json:"name,omitempty"`
}

// SessionInfo defines model for SessionInfo.
type SessionInfo struct {
	Email    string             `json:"email"`
	UserID   openapi_types.UUID `json:"userID"`
	UserSite *UserSite          `json:"userSite,omitempty"`
}

// StripeWebhookRequest defines model for StripeWebhookRequest.
type StripeWebhookRequest map[string]interface{}

// TemplateInfo defines model for TemplateInfo.
type TemplateInfo struct {
	Id int `json:"id"`

	// Preview url to site's html for preview
	Preview string `json:"preview"`

	// Structure url to pages.json file
	Structure string `json:"structure"`

	// Styles url to css file
	Styles       string `json:"styles"`
	TemplateName string `json:"templateName"`
}

// UpdateSiteRequest defines model for UpdateSiteRequest.
type UpdateSiteRequest struct {
	Domain     *string                      `json:"domain,omitempty"`
	DomainType *UpdateSiteRequestDomainType `json:"domainType,omitempty"`
	Fields     *map[string]interface{}      `json:"fields,omitempty"`

	// FileID photo of a template
	FileID     *openapi_types.UUID         `json:"fileID,omitempty"`
	NewStatus  *UpdateSiteRequestNewStatus `json:"newStatus,omitempty"`
	TemplateID *uint8                      `json:"templateID,omitempty"`
}

// UpdateSiteRequestDomainType defines model for UpdateSiteRequest.DomainType.
type UpdateSiteRequestDomainType string

// UpdateSiteRequestNewStatus defines model for UpdateSiteRequest.NewStatus.
type UpdateSiteRequestNewStatus string

// UpdateSiteResponse defines model for UpdateSiteResponse.
type UpdateSiteResponse struct {
	SiteID uint64 `json:"siteID"`
}

// UpdateTemplateRequest defines model for UpdateTemplateRequest.
type UpdateTemplateRequest struct {
	// FileID photo of a template
	FileID *openapi_types.UUID `json:"fileID,omitempty"`

	// Name template's name
	Name *string `json:"name,omitempty"`
}

// UserSite defines model for UserSite.
type UserSite struct {
	SiteID uint64 `json:"siteID"`
}

// VerifyCode defines model for VerifyCode.
type VerifyCode struct {
	Code string `json:"code"`
}

// VerifyOauthToken defines model for VerifyOauthToken.
type VerifyOauthToken struct {
	IdToken  string                   `json:"idToken"`
	Provider VerifyOauthTokenProvider `json:"provider"`
}

// VerifyOauthTokenProvider defines model for VerifyOauthToken.Provider.
type VerifyOauthTokenProvider string

// BadRequestError defines model for BadRequestError.
type BadRequestError = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFoundError defines model for NotFoundError.
type NotFoundError = ErrorResponse

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = ErrorResponse

// FileUploadMultipartBody defines parameters for FileUpload.
type FileUploadMultipartBody struct {
	File *openapi_types.File `json:"file,omitempty"`

	// Metadata json object with file metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
}

// EnrichContentJSONRequestBody defines body for EnrichContent for application/json ContentType.
type EnrichContentJSONRequestBody = EnrichContentRequest

// CreateConfirmationJSONRequestBody defines body for CreateConfirmation for application/json ContentType.
type CreateConfirmationJSONRequestBody = CreateConfirmation

// VerifyOauthTokenJSONRequestBody defines body for VerifyOauthToken for application/json ContentType.
type VerifyOauthTokenJSONRequestBody = VerifyOauthToken

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSession

// DeleteUserJSONRequestBody defines body for DeleteUser for application/json ContentType.
type DeleteUserJSONRequestBody = DeleteUserRequest

// VerifyUserJSONRequestBody defines body for VerifyUser for application/json ContentType.
type VerifyUserJSONRequestBody = VerifyCode

// FileUploadMultipartRequestBody defines body for FileUpload for multipart/form-data ContentType.
type FileUploadMultipartRequestBody FileUploadMultipartBody

// CreatePaymentJSONRequestBody defines body for CreatePayment for application/json ContentType.
type CreatePaymentJSONRequestBody = CreatePaymentRequest

// HandleEventJSONRequestBody defines body for HandleEvent for application/json ContentType.
type HandleEventJSONRequestBody = StripeWebhookRequest

// CreateSiteJSONRequestBody defines body for CreateSite for application/json ContentType.
type CreateSiteJSONRequestBody = CreateSiteRequest

// UpdateSiteJSONRequestBody defines body for UpdateSite for application/json ContentType.
type UpdateSiteJSONRequestBody = UpdateSiteRequest

// RebuildTemplatesJSONRequestBody defines body for RebuildTemplates for application/json ContentType.
type RebuildTemplatesJSONRequestBody = RebuildTemplatesRequest

// CreateTemplateJSONRequestBody defines body for CreateTemplate for application/json ContentType.
type CreateTemplateJSONRequestBody = CreateTemplateRequest

// ListTemplatesJSONRequestBody defines body for ListTemplates for application/json ContentType.
type ListTemplatesJSONRequestBody = ListTemplatePaginator

// UpdateTemplateJSONRequestBody defines body for UpdateTemplate for application/json ContentType.
type UpdateTemplateJSONRequestBody = UpdateTemplateRequest
