// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package dto

// Defines values for GetSiteResponseHealthCheckStatus.
const (
	Healthy        GetSiteResponseHealthCheckStatus = "Healthy"
	NotProvisioned GetSiteResponseHealthCheckStatus = "NotProvisioned"
	Unhealthy      GetSiteResponseHealthCheckStatus = "Unhealthy"
)

// Defines values for UpdateSiteRequestDomainType.
const (
	BringYourDomain UpdateSiteRequestDomainType = "BringYourDomain"
	DefaultDomain   UpdateSiteRequestDomainType = "DefaultDomain"
	SeparateDomain  UpdateSiteRequestDomainType = "SeparateDomain"
)

// Defines values for UpdateSiteRequestNewStatus.
const (
	AwaitingProvision UpdateSiteRequestNewStatus = "AwaitingProvision"
	Created           UpdateSiteRequestNewStatus = "Created"
	InCreation        UpdateSiteRequestNewStatus = "InCreation"
)

// CreateConfirmation defines model for CreateConfirmation.
type CreateConfirmation struct {
	Email  string `json:"email"`
	UserID string `json:"userID"`
}

// CreatePaymentRequest defines model for CreatePaymentRequest.
type CreatePaymentRequest struct {
	PlanID uint8 `json:"planID"`
	SiteID int64 `json:"siteID"`
}

// CreatePaymentResponse defines model for CreatePaymentResponse.
type CreatePaymentResponse struct {
	ClientSecret   *string `json:"clientSecret,omitempty"`
	SubscriptionID *string `json:"subscriptionID,omitempty"`
}

// CreateSession defines model for CreateSession.
type CreateSession struct {
	AccessToken  string `json:"accessToken"`
	IdToken      string `json:"idToken"`
	RefreshToken string `json:"refreshToken"`
}

// CreateSiteRequest defines model for CreateSiteRequest.
type CreateSiteRequest struct {
	// Fields json object with all widgets and fields of a site
	Fields     *map[string]interface{} `json:"fields,omitempty"`
	PlanID     uint8                   `json:"planID"`
	TemplateID uint8                   `json:"templateID"`
}

// CreateSiteResponse defines model for CreateSiteResponse.
type CreateSiteResponse struct {
	SiteID uint64 `json:"siteID"`
}

// CreateTemplateRequest defines model for CreateTemplateRequest.
type CreateTemplateRequest struct {
	// Fields json object with all widgets and fields of a site
	Fields map[string]interface{} `json:"fields"`

	// Name template's name
	Name string `json:"name"`
}

// CreateTemplateResponse defines model for CreateTemplateResponse.
type CreateTemplateResponse struct {
	Id uint8 `json:"id"`
}

// DomainAvailability defines model for DomainAvailability.
type DomainAvailability struct {
	Available bool `json:"available"`
}

// EnrichContentRequest defines model for EnrichContentRequest.
type EnrichContentRequest struct {
	Content string `json:"content"`
}

// EnrichContentResponse defines model for EnrichContentResponse.
type EnrichContentResponse struct {
	Enriched string `json:"enriched"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// GetSiteResponse defines model for GetSiteResponse.
type GetSiteResponse struct {
	CreatedAt         string                           `json:"createdAt"`
	HealthCheckStatus GetSiteResponseHealthCheckStatus `json:"healthCheckStatus"`
}

// GetSiteResponseHealthCheckStatus defines model for GetSiteResponse.HealthCheckStatus.
type GetSiteResponseHealthCheckStatus string

// PaymentStatusResponse defines model for PaymentStatusResponse.
type PaymentStatusResponse struct {
	PaymentIntentID     string `json:"paymentIntentID"`
	PaymentIntentStatus string `json:"paymentIntentStatus"`
	PaymentStatus       string `json:"paymentStatus"`
	Status              string `json:"status"`
}

// StripeWebhookRequest defines model for StripeWebhookRequest.
type StripeWebhookRequest map[string]interface{}

// TemplateInfo defines model for TemplateInfo.
type TemplateInfo struct {
	// Structure pages.json file
	Structure    string `json:"structure"`
	TemplateName string `json:"templateName"`
}

// UpdateSiteRequest defines model for UpdateSiteRequest.
type UpdateSiteRequest struct {
	Domain     *string                      `json:"domain,omitempty"`
	DomainType *UpdateSiteRequestDomainType `json:"domainType,omitempty"`
	Fields     *map[string]interface{}      `json:"fields,omitempty"`
	NewStatus  *UpdateSiteRequestNewStatus  `json:"newStatus,omitempty"`
	TemplateID uint8                        `json:"templateID"`
}

// UpdateSiteRequestDomainType defines model for UpdateSiteRequest.DomainType.
type UpdateSiteRequestDomainType string

// UpdateSiteRequestNewStatus defines model for UpdateSiteRequest.NewStatus.
type UpdateSiteRequestNewStatus string

// UpdateSiteResponse defines model for UpdateSiteResponse.
type UpdateSiteResponse struct {
	SiteID uint64 `json:"siteID"`
}

// VerifiedUser defines model for VerifiedUser.
type VerifiedUser struct {
	UserID string `json:"userID"`
}

// VerifyCode defines model for VerifyCode.
type VerifyCode struct {
	Code string `json:"code"`
}

// BadRequestError defines model for BadRequestError.
type BadRequestError = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = ErrorResponse

// EnrichContentJSONRequestBody defines body for EnrichContent for application/json ContentType.
type EnrichContentJSONRequestBody = EnrichContentRequest

// CreateConfirmationJSONRequestBody defines body for CreateConfirmation for application/json ContentType.
type CreateConfirmationJSONRequestBody = CreateConfirmation

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSession

// VerifyUserJSONRequestBody defines body for VerifyUser for application/json ContentType.
type VerifyUserJSONRequestBody = VerifyCode

// CreatePaymentJSONRequestBody defines body for CreatePayment for application/json ContentType.
type CreatePaymentJSONRequestBody = CreatePaymentRequest

// HandleEventJSONRequestBody defines body for HandleEvent for application/json ContentType.
type HandleEventJSONRequestBody = StripeWebhookRequest

// CreateSiteJSONRequestBody defines body for CreateSite for application/json ContentType.
type CreateSiteJSONRequestBody = CreateSiteRequest

// UpdateSiteJSONRequestBody defines body for UpdateSite for application/json ContentType.
type UpdateSiteJSONRequestBody = UpdateSiteRequest

// CreateTemplateJSONRequestBody defines body for CreateTemplate for application/json ContentType.
type CreateTemplateJSONRequestBody = CreateTemplateRequest
