// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package dto

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ProvisionSiteRequest defines model for ProvisionSiteRequest.
type ProvisionSiteRequest struct {
	DomainVariants []string `json:"domainVariants"`

	// Fields json object with all widgets and fields of a site
	Fields       map[string]interface{} `json:"fields"`
	SiteID       uint64                 `json:"siteID"`
	TemplateName string                 `json:"templateName"`
}

// ProvisionSiteResponse defines model for ProvisionSiteResponse.
type ProvisionSiteResponse struct {
	SiteID uint64 `json:"siteID"`
}

// ProvisionSiteJSONRequestBody defines body for ProvisionSite for application/json ContentType.
type ProvisionSiteJSONRequestBody = ProvisionSiteRequest
