openapi: 3.0.3
info:
  title: Site Creation API
  version: 1.0.0
  description: API for creating user sites with templates

paths:
  /sites:
    post:
      summary: Create a new site
      operationId: createSite
      tags:
        - Sites
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSiteRequest'
      responses:
        '201':
          description: Site created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSiteResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /sites/{id}:
    patch:
      summary: Update an existing site
      operationId: updateSite
      tags:
        - Sites
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: uint64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSiteRequest'
      responses:
        '200':
          description: Site updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSiteResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/InternalServerError'
    get:
      summary: Get info about an existing site
      operationId: getSite
      tags:
        - Sites
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: uint64
      responses:
        '200':
          description: Site info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSiteResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /ai/enrich:
    post:
      summary: Enrich some user provided info using AI
      operationId: enrichContent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnrichContentRequest'
      responses:
        '200':
          description: Content enriched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnrichContentResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /domain/check:
    post:
      summary: Checks domain availability
      description: Returns whether a domain is available or not
      operationId: checkDomain
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckDomainParams'
      responses:
        '200':
          description: Domain availability info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainAvailability'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /auth/token:
    post:
      summary: Gets an access token from oidc
      description: Returns access token for a specific code using authorization flow
      operationId: getToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthCode'
      responses:
        '200':
          description: Access token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessToken'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /payments:
    post:
      summary: Gets a client secret to create a payment
      description: Returns a client secret to create a checkout session for payment
      operationId: createPayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaymentRequest'
      responses:
        '200':
          description: Client secret for a checkout session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePaymentResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /payments/{id}:
    get:
      summary: Gets a payment checkout session info
      description: Returns a payment checkout session info
      operationId: getPaymentStatus
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: Client secret for a checkout session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentStatusResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /payments/webhook:
    post:
      summary: Listens for webhook requests from stripe
      operationId: handleEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StripeWebhookRequest'
      responses:
        '200':
          description: Client secret for a checkout session
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    CreateSiteRequest:
      type: object
      properties:
        templateID:
          type: integer
          format: uint8
          example: 1
        planID:
          type: integer
          format: uint8
        userID:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        fields:
          type: object
          description: json object with all widgets and fields of a site
          additionalProperties: true
      required:
        - templateID
        - userID
        - planID

    CreateSiteResponse:
      type: object
      properties:
        siteID:
          type: integer
          format: uint64
          example: 123456
      required:
        - siteID

    UpdateSiteRequest:
      type: object
      properties:
        templateID:
          type: integer
          format: uint8
          example: 2
        domainType:
          type: string
          enum: [DefaultDomain, SeparateDomain, BringYourDomain]
        domain:
          type: string
          example: "example.com"
        newStatus:
          type: string
          enum: [InCreation, AwaitingProvision, Created]
          example: "Created"
        fields:
          type: object
          additionalProperties: true
          example:
            title: "My Site"
            theme: "dark"
            customSetting:
              nested: true
              list: [ 1, 2, 3 ]
      required:
        - templateID

    UpdateSiteResponse:
      type: object
      properties:
        siteID:
          type: integer
          format: uint64
          example: 123456
      required:
        - siteID

    EnrichContentRequest:
      type: object
      properties:
        content:
          type: string
          example: "Some info about user"
      required:
        - content
        # TODO: add some metadata for AI to better understand what kind of enrichment to perform

    EnrichContentResponse:
      type: object
      properties:
        enriched:
          type: string
          example: "Some info about user enriched"
      required:
        - enriched

    CheckDomainParams:
      type: object
      properties:
        domain:
          type: string
      required:
        - domain

    GetSiteResponse:
      type: object
      properties:
        healthCheckStatus:
          type: string
          enum: [Healthy, Unhealthy, NotProvisioned]
        createdAt:
          type: string
          format: string
      required:
        - healthCheckStatus
        - createdAt

    DomainAvailability:
      type: object
      properties:
        available:
          type: boolean
          example: true
      required:
        - available

    AuthCode:
      type: object
      properties:
        code:
          type: string
          example: 3ad6c7c6-c119-4759-9f04-4e985a6a11e7
      required:
        - code

    AccessToken:
      type: object
      properties:
        token:
          type: string
          example: 3ad6c7c6-c119-4759-9f04-4e985a6a11e7
      required:
        - token

    CreatePaymentRequest:
      type: object
      properties:
        planID:
          type: integer
          format: uint8
          example: 2
        siteID:
          type: integer
          format: int64
          example: 21345
      required:
        - planID
        - siteID

    CreatePaymentResponse:
      type: object
      properties:
        clientSecret:
          type: string
          example: asdsad
      required:
        - clientSecret

    PaymentStatusResponse:
      type: object
      properties:
        status:
          type: string
          example: Success
        paymentStatus:
          type: string
        paymentIntentID:
          type: string
        paymentIntentStatus:
          type: string
      required:
        - status
        - paymentStatus
        - paymentIntentID
        - paymentIntentStatus

    StripeWebhookRequest:
      type: object
      additionalProperties: true

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "invalid request"
      required:
        - error
  responses:
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    BadRequestError:
      description: Invalid request body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'