name: Builder

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    environment: test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Download deps
        run: go mod download

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...