name: Builder

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    environment: test
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
      COGNITO_ISSUER: ${{ secrets.COGNITO_ISSUER }}
      COGNITO_POOL_ID: ${{ secrets.COGNITO_POOL_ID }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Download deps
        run: go mod download

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...